version: "3.8"

services:
  trainer:
    build: .
    image: myteam-solution:latest
    container_name: trainer-container
    command: bash ./run.sh
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
